### ISSUE TITLE
enhancement: merge leagueroll and leagueroll_random

### ISSUE THREAD

**Issue by mariogarridopt** [mariogarridopt/mariobot#9]
At the moment we have two commands for league of legends. This is too much, lets merge the features into one.

Commands:
- /leagueroll
- /leagueroll_random

**TODO**:
- [x] Remove one of the commands from `bot.py`;
- [x] Remove one of the functions from `roll.py`;
- [ ] Update README.md file to reflect this changes.

**Careful**:
There will be a conflict, because `leagueroll` uses a lane parameter and `leagueroll_random` doesn't.
For now, I will accept one of two ways to deal with this:
- Keep the behavior as `/leagueroll` and require a lane to be sent.
- Keep the behavior as `/leagueroll` and find a way to make lane optional.

**Tests**:
- [ ] After fixing this, edit the tests on `tests/roll_test.py`
